<div class="userprofile col-md-9">
	<h3><?php echo $teacher['firstname'].' '.$teacher['lastname']?></h3>
	<div class="userprofilebox clearfix">
		<div class="profilepicture col-md-3">
			<a href="">
				<img src="/images/user.png" class="userpicture defaultuserpic" width="100" height="100" />
			</a>
		</div>
		<div class="descriptionbox col-md-9">
			<div class="description"></div>
			<dl class="dl-horizontal">
				<dt>Country</dt><dd>Belgium</dd>
				<dt>Email address</dt><dd><a href="">test@ulb.ac.be</a></dd>
			</dl>
		</div>
	</div>
</div> 
<div class="col-md-3">
</div>