<?php 
if (is_null($name)){
	$name = 'mainb';
}?>
<div class="x_content">
<div class="col-md-6 col-sm-6 col-xs-12">
	<div id="<?php echo $name;?>"  style="height:350px;"></div>
</div>
<div class="col-md-6 col-sm-6 col-xs-12">
	<div class="col-xs-3">
    <!-- required for floating -->
    <!-- Nav tabs -->
	    <ul class="nav nav-tabs tabs-left">
	    <?php if (!is_null($avis)){ ?>
        	<li class="active"><a href="#avis" data-toggle="tab"><?php echo $this->getView()->translate('AVIS')?></a>
            </li>
        <?php } ?>
        <?php if (!is_null($comments)){ ?>
        	<li><a href="#comments" data-toggle="tab"><?php echo $this->getView()->translate('COMMENTS')?></a>
            </li>
        <?php } ?>
        <?php if (!is_null($resources)){ ?>
        	<li><a href="#resources" data-toggle="tab"><?php echo $this->getView()->translate('RESOURCES')?></a>
            </li>
        <?php } ?>
        </ul>
	</div>
	
	<div class="col-xs-9">
    <!-- Tab panes -->
    	<div class="tab-content">
    	<?php if (!is_null($avis)){ ?>
        	<div class="tab-pane active" id="home" style="height:350px;overflow-y: auto;">
	                   <p class="lead">Home tab</p>
                          <p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher
                            synth. Cosby sweater eu banh mi, qui irure terr. Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher
                            synth. Cosby sweater eu banh mi, qui irure terr. Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher
                            synth. Cosby sweater eu banh mi, qui irure terr. Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher
                            synth. Cosby sweater eu banh mi, qui irure terr. Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher
                            synth. Cosby sweater eu banh mi, qui irure terr. Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher
                            synth. Cosby sweater eu banh mi, qui irure terr. Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher
                            synth. Cosby sweater eu banh mi, qui irure terr.</p>
			</div>
		<?php } ?>
		<?php if (!is_null($avis)){ ?>
        	<div class="tab-pane active" id="home" style="height:350px;overflow-y: auto;">
	                   <p class="lead">Home tab</p>
                          <p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher
                            synth. Cosby sweater eu banh mi, qui irure terr. Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher
                            synth. Cosby sweater eu banh mi, qui irure terr. Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher
                            synth. Cosby sweater eu banh mi, qui irure terr. Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher
                            synth. Cosby sweater eu banh mi, qui irure terr. Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher
                            synth. Cosby sweater eu banh mi, qui irure terr. Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher
                            synth. Cosby sweater eu banh mi, qui irure terr. Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher
                            synth. Cosby sweater eu banh mi, qui irure terr.</p>
			</div>
		<?php } ?>
		<?php if (!is_null($avis)){ ?>
        	<div class="tab-pane active" id="home" style="height:350px;overflow-y: auto;">
	                   <p class="lead">Home tab</p>
                          <p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher
                            synth. Cosby sweater eu banh mi, qui irure terr. Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher
                            synth. Cosby sweater eu banh mi, qui irure terr. Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher
                            synth. Cosby sweater eu banh mi, qui irure terr. Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher
                            synth. Cosby sweater eu banh mi, qui irure terr. Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher
                            synth. Cosby sweater eu banh mi, qui irure terr. Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher
                            synth. Cosby sweater eu banh mi, qui irure terr. Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher
                            synth. Cosby sweater eu banh mi, qui irure terr.</p>
			</div>
		<?php } ?>
		<?php if (!is_null($avis)){ ?>
        	<div class="tab-pane active" id="home" style="height:350px;overflow-y: auto;">
	                   <p class="lead">Home tab</p>
                          <p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher
                            synth. Cosby sweater eu banh mi, qui irure terr. Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher
                            synth. Cosby sweater eu banh mi, qui irure terr. Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher
                            synth. Cosby sweater eu banh mi, qui irure terr. Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher
                            synth. Cosby sweater eu banh mi, qui irure terr. Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher
                            synth. Cosby sweater eu banh mi, qui irure terr. Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher
                            synth. Cosby sweater eu banh mi, qui irure terr. Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher
                            synth. Cosby sweater eu banh mi, qui irure terr.</p>
			</div>
		<?php } ?>
		</div>
	</div>	
</div>
</div>
<?php
$questionlabels = "";
$verygood = "";
$good = "";
$average = "";
$bad = "";
$na = "";
$i = 0;
foreach ($answers as $qid => $answer){
	if ($i != 0){
		$questionlabels .= ',';
		$verygood .= ',';
		$good .= ',';
		$average .= ',';
		$bad .= ',';
		$na .= ',';
	}
	$i++;
	$questionlabels .= '"Q'.$qid.'"';
	$verygood .= $answer['4'];
	$good .= $answer['3'];
	$average .= $answer['2'];
	$bad .= '-'.$answer['1'];
	$na .= $answer['5'];
}
?>
<script>
var option = {
	    tooltip : {
	        trigger: 'axis',
	        axisPointer : {            //
	            type : 'shadow'        //'line' | 'shadow'
	        }
	    },
	    legend: {
	        data:['average', 'good', 'very good', 'bad', 'not applicable']
	    },
	    toolbox: {
	        //show : true,
	        feature : {
	            //mark : {show: true},
	            //dataView : {show: true, readOnly: false},
	            //magicType : {show: true, type: ['line', 'bar']},
	            //restore : {show: true},
	            //saveAsImage : {show: true}
	        }
	    },
	    calculable : true,
	    xAxis : [
	        {
	            type : 'value',
	            axisLabel : {
		            formatter:'{value}%',
	            }
	        }
	    ],
	    yAxis : [
	        {
	            type : 'category',
	            axisTick : {show: false},
	            data : [<?php echo $questionlabels?>],
	            splitLine : {show : false}
	        }
	    ],
	    series : [
	        {
	            name:'average',
	            type:'bar',
	            stack: 'test',
	            barWidth : 20,
	            itemStyle: {normal: {
	                label : {show: false, position: 'inside'},
	                color : '#ffbf00'
	            }},
	            data:[<?php echo $average?>]
	        },
	        {
	            name:'good',
	            type:'bar',
	            stack: 'test',
	            barWidth : 20,
	            itemStyle: {normal: {
	                label : {show: false},
            		color : '#74df00'
	            }},
	            data:[<?php echo $good?>]
	        },
	        {
	            name:'very good',
	            type:'bar',
	            stack: 'test',
	            barWidth : 20,
	            itemStyle : { normal: {
		            label : {show: false, position: 'inside'},
		            color : '#347819'
			    }},
	            data:[<?php echo $verygood?>]
	        },
	        {
	            name:'bad',
	            type:'bar',
	            stack: 'test',
	            barWidth : 20,
	            itemStyle: {normal: {
	                label : {show: false, position: 'inside'},
            		color : '#df0101'
	            }},
	            data:[<?php echo $bad?>]
	        },
	        {
	            name:'not applicable',
	            type:'bar',
	            stack: 'test',
	            barWidth : 20,
	            itemStyle: {normal: {
	                label : {show: false, position: 'inside'},
	                color : '#848484'
	            }},
	            data:[<?php echo $na?>]
	        }
	    ]
	};

    	var theme = {

    	    bar: {
    	        itemStyle: {
    	            normal: {
    	                barBorderRadius: 2
    	            },
    	            emphasis: {
    	                barBorderRadius: 2
    	            }
    	        }
    	    },
    	    
    	};

    var echartBar = echarts.init(document.getElementById('<?php echo $name; ?>'), theme);
    echartBar.setOption(option, 'macarons');

</script>